# -*- coding: utf-8 -*-
"""
本地网页登录认证配置示例（请复制为 auth_config.py 后填写）。
"""

ACCOUNT_ID = "YOUR_ACCOUNT_ID"
AUTHORIZATION = "md_pss_id YOUR_AUTHORIZATION_TOKEN"
COOKIE = "YOUR_COOKIE_STRING"

DEFAULT_APP_ID = "YOUR_DEFAULT_APP_ID"
DEFAULT_WORKSHEET_ID = "YOUR_DEFAULT_WORKSHEET_ID"
DEFAULT_COVER_CID = "YOUR_DEFAULT_COVER_FIELD_CID"
