"""
HAP 视图类型定义 — 完整版（11 种，viewType 0-10）。

来源：
  - hap-utral-maker/api-specs/block1-private/worksheet/save-worksheet-view.md（6 种已录制）
  - SaveWorksheetView API 测试（viewType 6-10 全部可创建）
  - 明道云前端视图选择面板
  - 2026-04-03 API 实测（worksheetId=69cf74eef9434db36c6e0816）

说明：
  - PLANNABLE_VIEWS 是 AI 规划时应使用的视图子集
  - 每种视图标注了字段约束和二次保存配置
  - 完整 advancedSetting 参数详见 view_config_schema.py

advancedSetting 通用键（所有视图）：
  - enablerules: "1"=启用颜色规则（推荐始终设置）
  - navempty: "1"=显示空分组
  - detailbtns: "[]"=详情页按钮（JSON 数组字符串）
  - listbtns: "[]"=列表操作按钮（JSON 数组字符串）
  - coverstyle: 封面样式，表格/看板默认 '{"position":"1","style":3}'，画廊默认 '{"position":"2"}'
  - rowHeight: "0"=紧凑/"1"=中等/"2"=宽松/"3"=超高

groupView BUG 修复（2026-04-03）：
  - groupView JSON 必须使用紧凑格式（separators=(',',':')，无空格）
  - viewId 必须填当前视图的真实 ID（二次保存时）
"""

from __future__ import annotations

VIEW_REGISTRY = {
    0: {
        "name": "表格视图",
        "category": "basic",
        "verified": True,
        "requires_fields": [],
        "post_create": None,
        "auto_complete": "grouping",
        "doc": "默认视图。名称含'分组'时自动生成 groupView。需要单选字段(type=9/10/11)。",
        "advancedSetting_keys": {
            "groupView": "分组配置 JSON 字符串（紧凑格式，viewId=当前视图ID，需二次保存）",
            "groupsetting": "分组设置 JSON: [{controlId, filterType}]",
            "groupsorts": "分组排序 JSON: [{controlId, isAsc}]",
            "groupcustom": "自定义分组",
            "groupshow": "分组显示: '0'=全部, '1'=筛选, '2'=自定义",
            "groupfilters": "分组筛选条件 JSON 数组",
            "groupopen": "分组展开",
            "colorid": "记录颜色字段 ID",
            "coloritems": "颜色映射",
            "colortype": "'0'=按字段颜色, '1'=自定义",
            "enablerules": "'1'=启用颜色规则",
            "coverstyle": "封面样式，默认 '{\"position\":\"1\",\"style\":3}'",
            "navempty": "'1'=显示空分组",
            "shownullitem": "'1'=导航显示空项",
            "navsorts": "导航排序",
            "customnavs": "自定义导航项",
            "navlayer": "导航层级",
            "navshow": "导航显示: '0'=全部",
            "navfilters": "导航筛选条件 JSON",
            "usenav": "'0'/'1'=启用导航",
            "navsearchtype": "导航搜索类型",
            "detailbtns": "详情页按钮 JSON 数组字符串",
            "listbtns": "列表操作按钮 JSON 数组字符串",
        },
        "top_level_extra": {
            "rowHeight": "行高 0=紧凑/1=中等/2=宽松/3=超高（顶层参数）",
            "navGroup": "导航分组配置数组",
        },
    },
    1: {
        "name": "看板视图",
        "category": "basic",
        "verified": True,
        "requires_fields": ["single_select"],
        "post_create": None,
        "auto_complete": "viewControl",
        "doc": "必须设 viewControl 为单选字段(type=11) ID。无合适字段则不创建。",
        "advancedSetting_keys": {
            "viewtitle": "标题字段 ID",
            "abstract": "摘要字段 ID",
            "cardwidth": "卡片宽度: '1'-'4'",
            "navsorts": "看板列排序",
            "customitems": "自定义看板列",
            "navshow": "看板列显示: '0'=全部, '1'=筛选",
            "navfilters": "看板列筛选条件 JSON",
            "groupsetting": "分组设置 JSON",
            "groupsorts": "分组排序",
            "groupcustom": "自定义分组",
            "groupshow": "分组显示: '0'/'1'/'2'",
            "groupfilters": "分组筛选",
            "groupopen": "分组展开",
            "freezenav": "冻结看板列",
            "colorid": "记录颜色字段 ID",
            "coloritems": "颜色映射",
            "colortype": "'0'=按字段颜色, '1'=自定义",
            "showcount": "显示数量",
            "enablerules": "'1'=启用颜色规则",
            "coverstyle": "封面样式",
            "navempty": "'1'=显示空分组",
            "detailbtns": "详情页按钮 JSON",
            "listbtns": "列表操作按钮 JSON",
        },
        "top_level_extra": {
            "viewControl": "看板分组字段 ID（type=9/11 单选字段）",
            "coverCid": "封面字段 ID（可选）",
            "controlsSorts": "字段显示顺序数组",
        },
    },
    2: {
        "name": "层级视图",
        "category": "basic",
        "verified": True,
        "requires_fields": ["self_relation"],
        "post_create": {
            "editAttrs": ["childType", "layersControlId"],
            "fields": {"childType": 0, "layersControlId": "<self_relation_field_id>"},
        },
        "auto_complete": "hierarchy",
        "doc": "需要自关联字段(type=29, dataSource=本表)。二次保存 childType + layersControlId（顶层字段，不在 advancedSetting 内）。",
        "advancedSetting_keys": {
            "hierarchyViewType": "显示方式: '0'=树形, '1'=缩进, '2'=脑图, '3'=竖向树",
            "hierarchyViewConnectLine": "'1'=显示连接线",
            "defaultlayer": "默认展开层数: '1'-'4'",
            "defaultlayertime": "展开层数更新时间戳",
            "treestyle": "树形样式: '2'",
            "alternatecolor": "'1'=交替颜色",
            "titlewrap": "'1'=标题换行",
            "topshow": "顶级节点显示: '3'=筛选",
            "topfilters": "顶级节点筛选条件 JSON",
            "minHierarchyLevel": "最小层级数: '3'/'4'",
            "cardwidth": "卡片宽度: '1'-'4' 或像素值(200/320)",
            "abstract": "摘要字段 ID",
            "maxlinenum": "最大行数: 4/5",
            "refreshtime": "自动刷新秒数: '60'",
            "enablerules": "'1'=启用颜色规则",
            "navempty": "'1'=显示空节点",
            "detailbtns": "详情页按钮 JSON",
            "listbtns": "列表操作按钮 JSON",
        },
        "top_level_extra": {
            "childType": "0=自关联, 1=指定关联字段。通过 editAttrs 二次保存",
            "viewControl": "关联字段 ID（childType=1 时使用）",
            "layersControlId": "自关联字段 ID，通过 editAttrs 二次保存",
            "rowHeight": "行高 0/1/2",
        },
    },
    3: {
        "name": "画廊视图",
        "category": "basic",
        "verified": True,
        "requires_fields": [],
        "post_create": None,
        "auto_complete": None,
        "doc": "卡片画廊。可设 coverCid（顶层）为图片/附件字段。advancedSetting.coverstyle 默认 '{\"position\":\"2\"}'。",
        "advancedSetting_keys": {
            "viewtitle": "标题字段 ID",
            "abstract": "摘要字段 ID",
            "maxlinenum": "最大行数: 3/4",
            "cardwidth": "卡片宽度: '1'-'4'",
            "showcount": "显示数量: '2'/'3'",
            "groupsetting": "分组设置 JSON",
            "groupsorts": "分组排序",
            "groupcustom": "自定义分组",
            "groupshow": "分组显示: '0'/'1'/'2'",
            "groupfilters": "分组筛选 JSON（选项 key 数组）",
            "groupempty": "'1'=显示空分组",
            "groupopen": "分组展开: '1'/'3'",
            "controlstyle": "'1'=紧凑样式",
            "controlstyleapp": "'1'=移动端紧凑样式",
            "defaultsort": "默认排序 JSON: {controlId, isAsc}",
            "colorid": "记录颜色字段 ID",
            "coloritems": "颜色映射",
            "colortype": "'0'=字段颜色, '1'=自定义, '2'=其他",
            "shownullitem": "'1'=导航显示空项",
            "navsorts": "导航排序: '1'=自定义",
            "customnavs": "自定义导航项 JSON（选项 key 数组）",
            "navlayer": "导航层级",
            "navshow": "导航显示: '0'=全部",
            "navfilters": "导航筛选 JSON",
            "usenav": "'0'/'1'=启用导航",
            "navsearchtype": "导航搜索类型",
            "navwidth": "导航宽度像素: '150'",
            "coverstyle": "封面样式，画廊默认 '{\"position\":\"2\"}'",
            "enablerules": "'1'=启用颜色规则",
            "navempty": "'1'=显示空分组",
        },
        "top_level_extra": {
            "coverCid": "封面字段 ID（图片/附件字段，可选）",
            "navGroup": "导航分组配置数组",
            "controls": "隐藏字段 ID 数组",
            "showControls": "显示字段数组",
        },
    },
    4: {
        "name": "日历视图",
        "category": "basic",
        "verified": True,
        "requires_fields": ["date"],
        "post_create": {
            "editAttrs": ["advancedSetting"],
            "editAdKeys": ["calendarcids"],
            "fields": {"calendarcids": '[{"begin":"<date_field_id>","end":""}]'},
        },
        "auto_complete": "calendar",
        "doc": "需要日期字段(type=15/16)。二次保存 calendarcids（紧凑 JSON 字符串）。支持多日期：[{\"begin\":\"id1\",\"end\":\"id2\"}]。",
        "advancedSetting_keys": {
            "calendarcids": "日历字段配置 JSON: [{begin, end, mark}]，二次保存",
            "calendarType": "日历类型: '1'=月, '2'=周",
            "weekbegin": "每周起始日: '2'=周一, '7'=周日",
            "unweekday": "隐藏星期: '7'=周日, '67'=周六日, '73'=周三日",
            "showtime": "显示时间段: '08:00-18:00'",
            "unlunar": "'0'=显示农历",
            "hour24": "'1'=24小时制",
            "showall": "'0'/'1'=显示全部",
            "viewtitle": "标题字段 ID（$包裹）",
            "abstract": "摘要字段 ID",
            "maxlinenum": "最大行数",
            "refreshtime": "自动刷新秒数: '30'",
            "defaultsort": "默认排序 JSON: {controlId, isAsc}",
            "closedefsort": "'1'=关闭默认排序",
            "colorid": "记录颜色字段 ID",
            "coloritems": "颜色映射",
            "colortype": "'0'=字段颜色, '1'=自定义, '2'=其他",
            "enablebtn": "'1'=启用快筛按钮",
            "fastrequired": "'1'=快筛必填",
            "clicksearch": "'1'=点击搜索",
            "requiredcids": "必填字段 ID JSON 数组",
            "enablerules": "'1'=启用颜色规则",
            "rowHeight": "行高",
        },
    },
    5: {
        "name": "甘特图",
        "category": "basic",
        "verified": True,
        "requires_fields": ["date", "date"],
        "post_create": {
            "editAttrs": ["advancedSetting"],
            "editAdKeys": ["begindate", "enddate"],
            "fields": {"begindate": "<date_field_1>", "enddate": "<date_field_2>"},
        },
        "auto_complete": "gantt",
        "doc": "需要开始/结束日期字段(type=15/16)。二次保存 begindate + enddate。不设 coverstyle。",
        "advancedSetting_keys": {
            "begindate": "开始日期字段 ID，二次保存",
            "enddate": "结束日期字段 ID，二次保存",
            "milepost": "里程碑字段 ID（Checkbox类型）",
            "navtitle": "左侧列表标题字段 ID",
            "calendartype": "时间粒度: '1'=日, '2'=周, '3'=月, '4'=年",
            "unweekday": "隐藏星期: '67'=周六日, '675'=+周五, '6754'=+周四",
            "showgroupcolor": "'1'=显示分组颜色",
            "viewtitle": "甘特条标题字段 ID（$包裹）",
            "abstract": "摘要字段 ID",
            "refreshtime": "自动刷新秒数: '30'",
            "colorid": "记录颜色字段 ID",
            "coloritems": "颜色映射 JSON 数组（选项 key）",
            "colortype": "'0'=按字段颜色",
            "navshow": "分组显示: '0'=全部, '1'=筛选",
            "navfilters": "分组筛选条件 JSON",
            "navsorts": "分组排序",
            "customitems": "自定义分组项",
            "enablerules": "'1'=启用颜色规则",
            "navempty": "'1'=显示空分组",
            "rowHeight": "行高 0/1/2/3",
        },
        "top_level_extra": {
            "viewControl": "分组字段 ID（单选等）",
            "showControls": "甘特条上显示的字段 ID 数组",
        },
    },
    6: {
        "name": "详情视图",
        "category": "advanced",
        "verified": True,
        "requires_fields": [],
        "post_create": None,
        "auto_complete": None,
        "doc": "单条记录详情/表单视图。适合数据录入场景。支持 PC 多列布局（showpc+showRows）。",
        "advancedSetting_keys": {
            "showtitle": "'0'=隐藏标题, ''=显示",
            "showtoolbar": "'0'=隐藏工具栏, ''=显示",
            "viewtitle": "标题字段 ID",
            "abstract": "摘要字段 ID",
            "cardwidth": "卡片宽度: '1'-'4'",
            "maxlinenum": "最大行数: 2/3",
            "refreshtime": "自动刷新秒数: '60'",
            "colorid": "记录颜色字段 ID",
            "coloritems": "颜色映射",
            "colortype": "'0'=字段颜色, '1'=自定义, '2'=其他",
            "enablerules": "'1'=启用颜色规则",
            "detailbtns": "详情页按钮 JSON",
            "listbtns": "列表操作按钮 JSON",
        },
        "top_level_extra": {
            "childType": "1=单条详情, 2=列表+详情",
        },
    },
    7: {
        "name": "资源视图",
        "category": "advanced",
        "verified": True,
        "requires_fields": ["collaborator_or_select", "date"],
        "post_create": {
            "editAttrs": ["viewControl", "advancedSetting"],
            "editAdKeys": ["begindate", "enddate", "navshow", "navfilters"],
            "fields": {
                "viewControl": "<member_or_select_field_id>",
                "begindate": "<date_field_1>",
                "enddate": "<date_field_2>",
            },
        },
        "auto_complete": "resource",
        "doc": "按成员/字段分组的时间线视图。viewControl 设分组字段，advancedSetting 里 begindate/enddate 设日期范围。",
        "advancedSetting_keys": {
            "begindate": "开始日期字段 ID，二次保存",
            "enddate": "结束日期字段 ID，二次保存",
            "calendarType": "时间粒度: '0'=自动, '1'=日, '2'=周, '3'=月",
            "weekbegin": "每周起始日: '1'=周一...'7'=周日",
            "unweekday": "隐藏周末: '67'=隐藏周六日",
            "showtime": "显示时间段: '02:00-08:00'",
            "hour24": "'1'=24小时制",
            "navshow": "分组显示: '0'=全部, '1'=筛选",
            "navfilters": "分组筛选条件 JSON",
            "viewtitle": "标题字段 ID（$包裹）",
            "colorid": "记录颜色字段 ID",
            "coloritems": "颜色映射",
            "colortype": "'0'=按字段颜色, '1'=自定义, '2'=其他",
            "enablerules": "'1'=启用颜色规则",
        },
        "top_level_extra": {
            "viewControl": "分组字段 ID（成员/单选等），二次保存",
            "rowHeight": "行高 0=紧凑/1=中等/2=宽松",
        },
    },
    8: {
        "name": "地图视图",
        "category": "advanced",
        "verified": True,
        "requires_fields": ["location"],
        "post_create": None,
        "auto_complete": None,
        "doc": "地图视图(viewType=8)。viewControl 设定位字段 ID。支持标记样式、地图定位等。",
        "advancedSetting_keys": {
            "latlng": "指定地理位置字段 ID（type=24 地区 或 type=40 定位），可选",
            "tagType": "标记样式: 1=图标, 2=颜色标记",
            "tagcolorid": "标记颜色字段 ID",
            "maplocation": "地图定位 JSON: {type:2, location:1=指定/2=当前, value:经纬度}",
            "viewtitle": "标题字段 ID",
            "abstract": "摘要字段 ID",
            "maxlinenum": "最大行数: 3/4/5",
            "refreshtime": "自动刷新秒数: '30'/'60'",
            "colorid": "记录颜色字段 ID",
            "coloritems": "颜色映射",
            "colortype": "'0'=按字段颜色, '1'=自定义, '2'=其他",
            "enablerules": "'1'=启用颜色规则",
            "navempty": "'1'=显示空分组",
        },
        "top_level_extra": {
            "viewControl": "定位字段 ID，二次保存",
            "coverCid": "封面字段 ID",
            "showControlName": "是否显示字段名",
        },
    },
}

# 便捷映射
ALLOWED_VIEW_TYPES: set[str] = {str(k) for k in VIEW_REGISTRY}
VIEW_TYPE_NAMES: dict[int, str] = {k: v["name"] for k, v in VIEW_REGISTRY.items()}

# AI 规划时应使用的视图子集（全部 9 种）
PLANNABLE_VIEWS: set[int] = set(VIEW_REGISTRY.keys())
